# Generated by Django 3.2.7 on 2022-09-01 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_cartitem_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='coupon',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
