# Generated by Django 3.2.7 on 2022-09-04 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_coupon'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=200)),
                ('comment', models.CharField(max_length=200)),
                ('returnstatus', models.CharField(choices=[('Waiting', 'Waiting'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Processing', max_length=200)),
                ('return_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.orderproduct')),
            ],
        ),
    ]
