# Generated by Django 3.2.7 on 2022-08-24 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_subcategory'),
        ('store', '0003_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(null='false', on_delete=django.db.models.deletion.CASCADE, to='category.subcategory'),
            preserve_default='false',
        ),
    ]
