# Generated by Django 3.2.7 on 2022-09-01 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(max_length=8)),
                ('is_expired', models.BooleanField(default=False)),
                ('disccount', models.IntegerField(default=0)),
                ('minimum_amount', models.IntegerField(default=500)),
                ('maximum_amount', models.IntegerField(null=True)),
            ],
        ),
    ]
