# Generated by Django 3.2.7 on 2022-08-31 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_subcategory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='discount',
            field=models.IntegerField(default=0),
        ),
    ]
