# Generated by Django 3.2.7 on 2022-08-10 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_account_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='account',
            name='uid',
        ),
    ]
