# Generated by Django 3.2.7 on 2022-08-12 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20220810_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='otp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
